using System.Linq;
using Microsoft.EntityFrameworkCore;
using Web.Data;
using Web.Models;

namespace Web.Services;

public class ChatService
{
    private readonly ApplicationDbContext _context;

    public ChatService(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<List<Chat>> GetChatsForUserAsync(long userId)
    {
        return await _context.Chats
            .AsNoTracking() // Read-only query - no change tracking needed
            .Where(c => c.UserId == userId)
            .OrderByDescending(c => c.CreatedAt)
            .ToListAsync();
    }

    public async Task<Chat> CreateNewChatAsync(long userId, string? chatName = null)
    {
        var chat = new Chat
        {
            // Id will be auto-generated by database
            UserId = userId,
            Name = string.IsNullOrWhiteSpace(chatName) ? "New Chat" : chatName.Trim(),
            CreatedAt = DateTimeOffset.UtcNow
        };

        _context.Chats.Add(chat);
        await _context.SaveChangesAsync();

        return chat;
    }

    public async Task<List<Message>> GetMessagesAsync(long chatId, long userId)
    {
        // SECURITY: Only return messages from chats that belong to the user
        // First verify the chat exists and belongs to the user
        var chat = await _context.Chats
            .AsNoTracking()
            .FirstOrDefaultAsync(c => c.Id == chatId && c.UserId == userId);
        
        if (chat == null)
        {
            // Chat doesn't exist or doesn't belong to user - return empty list
            return new List<Message>();
        }
        
        // Chat belongs to user - return messages
        return await _context.Messages
            .AsNoTracking() // Read-only query - no change tracking needed
            .Include(m => m.Sender) // Include must come before OrderBy for better performance
            .Where(m => m.ChatId == chatId)
            .OrderBy(m => m.CreatedAt)
            .ToListAsync();
    }

    public async Task<Chat?> GetChatByIdAsync(long chatId, long userId)
    {
        return await _context.Chats
            .AsNoTracking() // Read-only query - no change tracking needed
            .FirstOrDefaultAsync(c => c.Id == chatId && c.UserId == userId);
    }
}

